db:
  user: 'shibui_planner_stillsport'
  pw: '0b5c3f5145731ff1fe2072716cd15895e7b0a402'
  host: 'zgzufe.h.filess.io'
  db: 'shibui_planner_stillsport'
  port: 3307

tables:
  user: 'mmungoshi_user'
  task: 'mmungoshi_task'
  user_task: 'mmungoshi_user_task'
  feedback: 'mmungoshi_feedback'
